In [103]:
import tensorflow as tf
import numpy as np
# what is a tensor? - A tensor is a data structure which is like an array which can be multidimensional.
# rank of tensor corresponds to the number of dimensions it has, for ex: a scalar has 0 dimensions, a vector has 1 dimension, and a matrix has two dimensions

tensor_1d = tf.constant([1, 2, 3, 4])
print(tensor_1d)
tensor_numpy = tensor_1d.numpy()  # converts the tensor to numpy array by creating it's another copy of numpy array
print(tensor_numpy)

tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor_2d)

# variable tensor
variable_tensor = tf.Variable([[1, 2, 3], [23, 32, 4]]) # this creates a variable tensor
print(variable_tensor)
variable_tensor[0, 0].assign(10) # assigning a value at a position
print(variable_tensor)


sum_tensor = tf.concat([variable_tensor, tf.constant([[3,4,5]])], axis = 0)
print(sum_tensor) # adding two tensors

# 1D tensor of zeros
zeros_tensor = tf.zeros(shape=(3,))
# 2D tensor of ones
ones_tensor = tf.ones(shape=(2, 3))
# Random 1D tensor
random_tensor = tf.random.normal(shape=(3,))
# Random 2D tensor
random_matrix = tf.random.uniform(shape=(2, 3))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
[1 2 3 4]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [23, 32,  4]])>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10,  2,  3],
       [23, 32,  4]])>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10,  2,  3],
       [23, 32,  4]])>


In [81]:
# Layers
"""
forming a linear layer
One layer of a dense layer connects to every node of the previous layer

units: Integer, the number of neurons or nodes in the layer. This parameter determines the dimensionality of the output space.

activation: Activation function applied to the layer's output. If not specified (default is None), no activation function is applied (i.e., "linear" activation).

use_bias: Boolean, whether to include bias parameters in the layer. Bias is an additional learnable parameter that allows the layer to have an offset.

kernel_initializer: Initializer for the weight matrix (also called kernel). It specifies the method for initializing the weights of the layer. Common choices include 'glorot_uniform', 'glorot_normal', 'he_uniform', 'he_normal', etc.

bias_initializer: Initializer for the bias vector. It determines the method for initializing the bias values. Common choices include 'zeros', 'ones', 'constant', etc.
"""

a = tf.keras.layers.Dense(units=1, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros')

# after definition the layer is not built immediately (weights aren't initilized, or variables are not instantiated)
# it built when input shape is instaitiated using build function
# for layer to be built, we must either use a.build, or pass some tensor where model takes the input shape of the tensor

a.build(input_shape = (1, 1))  

a1 = a(np.array([[0]]))

print(a.get_weights())  

# set_weights takes a list of numpy arrays, where first argument in the list is the initilizer for weights (kernel) and second one is for bias
a.set_weights([np.array([[0]]), np.array([0])])  # here we have give a array of weights for kernel, and for bias

w = a.get_weights()
print(w)


[array([[1.036976]], dtype=float32), array([0.], dtype=float32)]
[array([[0.]], dtype=float32), array([0.], dtype=float32)]


In [82]:
# model definition

"""
A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor.
"""
model = tf.keras.Sequential(
	[
		# name is used to name the model
		tf.keras.layers.Dense(1, input_dim=1,  activation = 'sigmoid', name='L1')
	]
)

layer = model.get_layer('L1') # get_layer() function is used to get the reference to a existing layer, in case if we want to modify it
print(layer.get_weights())

# model.summary() shows the layers and number of parameters in the model
model.summary()

model.predict(np.array([0])) # predict() function is used to run inference on the model

[array([[0.1539675]], dtype=float32), array([0.], dtype=float32)]
Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


1/1 [==============================] - 0s 54ms/step


array([[0.5]], dtype=float32)